# Generated by Django 6.0.6 on 2026-06-05 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Ariana', 'Ariana - Aryanah'), ('Beja', 'Béja - Baja'), ('Ben_Arous', 'Ben Arous - Bin Arus'), ('Bizerte', 'Bizerte - Bizerta'), ('Gabes', 'Gabès - Qabis'), ('Gafsa', 'Gafsa - Qafsa'), ('Jendouba', 'Jendouba - Jandouba'), ('Kairouan', 'Kairouan - al-Qayrawan'), ('Kasserine', 'Kasserine - Ksar Sin'), ('Kebili', 'Kébili - Qibili'), ('Kef', 'Le Kef - al-Kaf'), ('Mahdia', 'Mahdia - al-Mahdiya'), ('Manouba', 'La Manouba - al-Manubah'), ('Medenine', 'Medenine - Madanīn'), ('Monastir', 'Monastir - al-Munastir'), ('Nabeul', 'Nabeul - Nabul'), ('Sfax', 'Sfax - Safaqis'), ('Sidi_Bouzid', 'Sidi Bouzid - Sidi Bouzid'), ('Siliana', 'Siliana - Siliana'), ('Sousse', 'Sousse - Susa'), ('Tataouine', 'Tataouine - Tatawin'), ('Tozeur', 'Tozeur - Tūzūr'), ('Tunis', 'Tunis - Tunis'), ('Zaghouan', 'Zaghouan - Zaghouan')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_size', models.CharField(blank=True, max_length=50)),
                ('selected_color', models.CharField(blank=True, max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
        ),
    ]
